from datetime import datetime
from pathlib import Path
import sys
from typing import Any, Dict, List


CURRENT_DIR = Path(__file__).resolve().parent
BACKEND_DIR = CURRENT_DIR.parent
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

from app.database import Base, SessionLocal, get_default_engine
from app.models.bom import BOMHeader, BOMItem, Material
from app.services.plm_service import PLMService
from app.services.schema_compat_service import ensure_schema_compatibility


MATERIALS: List[Dict[str, Any]] = [
    {
        "code": "ASM-SRV-1001",
        "name": "伺服传动总成",
        "specification": "ASM-SRV-1001",
        "category": "成品",
        "unit": "SET",
        "safety_stock": 1,
        "current_stock": 0,
        "reserved_stock": 0,
        "incoming_stock": 1,
        "lead_time_days": 20,
        "drawing_no": "DWG-ASM-SRV-1001",
        "revision": "B",
        "material_type": "FINISHED",
        "description": "包装装备用非标伺服传动总成样例，用于演示 EBOM/PBOM 管理。",
    },
    {
        "code": "SUB-DRV-2100",
        "name": "传动子装配",
        "specification": "SUB-DRV-2100",
        "category": "半成品",
        "unit": "SET",
        "safety_stock": 0,
        "current_stock": 1,
        "reserved_stock": 0,
        "incoming_stock": 0,
        "lead_time_days": 8,
        "drawing_no": "DWG-SUB-DRV-2100",
        "revision": "B",
        "material_type": "SUB",
        "description": "包含壳体、主轴、轴承与联轴器的关键子装配。",
    },
    {
        "code": "CAS-3100",
        "name": "铸铝壳体",
        "specification": "AL-356-T6",
        "category": "自制件",
        "unit": "PCS",
        "safety_stock": 4,
        "current_stock": 10,
        "reserved_stock": 2,
        "incoming_stock": 3,
        "lead_time_days": 10,
        "drawing_no": "DWG-CAS-3100",
        "revision": "A",
        "material_type": "RAW",
        "description": "机加工后作为传动总成壳体使用。",
    },
    {
        "code": "SHA-3200",
        "name": "主轴",
        "specification": "40Cr φ28x286",
        "category": "自制件",
        "unit": "PCS",
        "safety_stock": 5,
        "current_stock": 8,
        "reserved_stock": 1,
        "incoming_stock": 0,
        "lead_time_days": 6,
        "drawing_no": "DWG-SHA-3200",
        "revision": "B",
        "material_type": "RAW",
        "description": "热处理后用于总成传动输出。",
    },
    {
        "code": "BRG-6205",
        "name": "深沟球轴承 6205",
        "specification": "6205-2RS",
        "category": "标准件",
        "unit": "PCS",
        "safety_stock": 20,
        "current_stock": 36,
        "reserved_stock": 4,
        "incoming_stock": 12,
        "lead_time_days": 3,
        "drawing_no": "STD-BRG-6205",
        "revision": "A",
        "material_type": "STD",
        "description": "关键标准件，承载主轴旋转。",
    },
    {
        "code": "CPL-3300",
        "name": "弹性联轴器",
        "specification": "D28-L35",
        "category": "标准件",
        "unit": "PCS",
        "safety_stock": 8,
        "current_stock": 10,
        "reserved_stock": 1,
        "incoming_stock": 4,
        "lead_time_days": 4,
        "drawing_no": "STD-CPL-3300",
        "revision": "A",
        "material_type": "STD",
        "description": "用于电机与主轴之间的柔性连接。",
    },
    {
        "code": "FLT-3400",
        "name": "安装法兰",
        "specification": "Q235B t12",
        "category": "自制件",
        "unit": "PCS",
        "safety_stock": 6,
        "current_stock": 5,
        "reserved_stock": 0,
        "incoming_stock": 3,
        "lead_time_days": 4,
        "drawing_no": "DWG-FLT-3400",
        "revision": "A",
        "material_type": "RAW",
        "description": "用于总成与主机机架连接。",
    },
    {
        "code": "RNG-3500",
        "name": "密封挡圈",
        "specification": "NBR-35",
        "category": "标准件",
        "unit": "PCS",
        "safety_stock": 20,
        "current_stock": 26,
        "reserved_stock": 2,
        "incoming_stock": 6,
        "lead_time_days": 3,
        "drawing_no": "STD-RNG-3500",
        "revision": "A",
        "material_type": "STD",
        "description": "改善防尘和润滑保持性能。",
    },
    {
        "code": "MTR-4000",
        "name": "750W 伺服电机",
        "specification": "AC750W-220V",
        "category": "外购件",
        "unit": "PCS",
        "safety_stock": 2,
        "current_stock": 2,
        "reserved_stock": 0,
        "incoming_stock": 2,
        "lead_time_days": 12,
        "drawing_no": "PUR-MTR-4000",
        "revision": "A",
        "material_type": "STD",
        "description": "关键外购件，需提前锁定采购交期。",
    },
    {
        "code": "ENC-4100",
        "name": "编码器组件",
        "specification": "17bit ABS",
        "category": "外购件",
        "unit": "PCS",
        "safety_stock": 2,
        "current_stock": 3,
        "reserved_stock": 0,
        "incoming_stock": 1,
        "lead_time_days": 8,
        "drawing_no": "PUR-ENC-4100",
        "revision": "A",
        "material_type": "STD",
        "description": "用于位移反馈的编码器组件。",
    },
    {
        "code": "BLT-M8X25",
        "name": "内六角螺栓 M8x25",
        "specification": "12.9级",
        "category": "标准件",
        "unit": "PCS",
        "safety_stock": 200,
        "current_stock": 500,
        "reserved_stock": 48,
        "incoming_stock": 300,
        "lead_time_days": 2,
        "drawing_no": "STD-BLT-M8X25",
        "revision": "A",
        "material_type": "STD",
        "description": "总装与法兰连接通用紧固件。",
    },
    {
        "code": "WSH-M8",
        "name": "平垫圈 M8",
        "specification": "304",
        "category": "标准件",
        "unit": "PCS",
        "safety_stock": 200,
        "current_stock": 500,
        "reserved_stock": 50,
        "incoming_stock": 200,
        "lead_time_days": 2,
        "drawing_no": "STD-WSH-M8",
        "revision": "A",
        "material_type": "STD",
        "description": "与 M8 紧固件配套使用。",
    },
    {
        "code": "JIG-CLP-2001",
        "name": "夹紧治具总成",
        "specification": "JIG-CLP-2001",
        "category": "成品",
        "unit": "SET",
        "safety_stock": 1,
        "current_stock": 0,
        "reserved_stock": 0,
        "incoming_stock": 0,
        "lead_time_days": 7,
        "drawing_no": "DWG-JIG-CLP-2001",
        "revision": "A",
        "material_type": "FINISHED",
        "description": "装配工装治具，用于展示多产品 BOM 列表。",
    },
    {
        "code": "JAW-3600",
        "name": "夹爪底座",
        "specification": "45# φ110",
        "category": "自制件",
        "unit": "PCS",
        "safety_stock": 3,
        "current_stock": 4,
        "reserved_stock": 0,
        "incoming_stock": 2,
        "lead_time_days": 5,
        "drawing_no": "DWG-JAW-3600",
        "revision": "A",
        "material_type": "RAW",
        "description": "治具主体底座，机加工件。",
    },
    {
        "code": "CYL-5200",
        "name": "气缸组件",
        "specification": "SC50x100",
        "category": "外购件",
        "unit": "PCS",
        "safety_stock": 2,
        "current_stock": 2,
        "reserved_stock": 0,
        "incoming_stock": 1,
        "lead_time_days": 5,
        "drawing_no": "PUR-CYL-5200",
        "revision": "A",
        "material_type": "STD",
        "description": "夹紧动作执行元件。",
    },
    {
        "code": "SNS-5300",
        "name": "行程传感器",
        "specification": "PNP M12",
        "category": "外购件",
        "unit": "PCS",
        "safety_stock": 2,
        "current_stock": 6,
        "reserved_stock": 1,
        "incoming_stock": 2,
        "lead_time_days": 4,
        "drawing_no": "PUR-SNS-5300",
        "revision": "A",
        "material_type": "STD",
        "description": "用于夹紧位置反馈。",
    },
]


BOM_DEFINITIONS: List[Dict[str, Any]] = [
    {
        "header": {
            "product_code": "ASM-SRV-1001",
            "product_name": "伺服传动总成",
            "version": "v1.0",
            "bom_type": "EBOM",
            "status": "RELEASED",
            "description": "首版工程 BOM，用于方案评审及早期采购测算。",
            "is_active": False,
            "product_family": "包装机模组",
            "business_unit": "智能装备事业部",
            "project_code": "PRJ-2026-001",
            "plant_code": "M01",
            "discipline": "机械装配",
            "source_system": "SOLIDWORKS",
            "source_file": "SolidWorks/ASM-SRV-1001_v1.0.SLDASM",
            "sync_status": "SYNCED",
            "cad_document_no": "DWG-ASM-SRV-1001",
            "released_by": "PLM自动同步",
            "last_synced_at": datetime(2026, 4, 23, 10, 0, 0),
        },
        "items": [
            {
                "parent_item_code": "ASM-SRV-1001",
                "child_item_code": "SUB-DRV-2100",
                "quantity": 1,
                "find_number": "001",
                "component_type": "KEY",
                "item_category": "Assembly",
                "procurement_type": "MAKE",
                "unit_price": 1850,
                "source_reference": "CAD-ASM-SRV-1001-001",
                "material_name": "传动子装配",
                "specification": "SUB-DRV-2100",
                "unit": "SET",
                "drawing_no": "DWG-SUB-DRV-2100",
                "revision": "B",
            },
            {
                "parent_item_code": "ASM-SRV-1001",
                "child_item_code": "MTR-4000",
                "quantity": 1,
                "find_number": "002",
                "component_type": "KEY",
                "item_category": "Purchased",
                "procurement_type": "BUY",
                "loss_rate": 0.01,
                "unit_price": 1280,
                "source_reference": "CAD-ASM-SRV-1001-002",
                "material_name": "750W 伺服电机",
                "specification": "AC750W-220V",
                "unit": "PCS",
                "drawing_no": "PUR-MTR-4000",
                "revision": "A",
            },
            {
                "parent_item_code": "ASM-SRV-1001",
                "child_item_code": "ENC-4100",
                "quantity": 1,
                "find_number": "003",
                "component_type": "NORMAL",
                "item_category": "Purchased",
                "procurement_type": "BUY",
                "unit_price": 420,
                "source_reference": "CAD-ASM-SRV-1001-003",
                "material_name": "编码器组件",
                "specification": "17bit ABS",
                "unit": "PCS",
                "drawing_no": "PUR-ENC-4100",
                "revision": "A",
            },
            {
                "parent_item_code": "ASM-SRV-1001",
                "child_item_code": "BLT-M8X25",
                "quantity": 8,
                "find_number": "004",
                "component_type": "NORMAL",
                "item_category": "Standard",
                "procurement_type": "BUY",
                "loss_rate": 0.03,
                "unit_price": 1.6,
                "source_reference": "CAD-ASM-SRV-1001-004",
                "material_name": "内六角螺栓 M8x25",
                "specification": "12.9级",
                "unit": "PCS",
                "drawing_no": "STD-BLT-M8X25",
                "revision": "A",
            },
            {
                "parent_item_code": "ASM-SRV-1001",
                "child_item_code": "WSH-M8",
                "quantity": 8,
                "find_number": "005",
                "component_type": "NORMAL",
                "item_category": "Standard",
                "procurement_type": "BUY",
                "loss_rate": 0.03,
                "unit_price": 0.35,
                "source_reference": "CAD-ASM-SRV-1001-005",
                "material_name": "平垫圈 M8",
                "specification": "304",
                "unit": "PCS",
                "drawing_no": "STD-WSH-M8",
                "revision": "A",
            },
            {
                "parent_item_code": "SUB-DRV-2100",
                "child_item_code": "CAS-3100",
                "quantity": 1,
                "find_number": "101",
                "component_type": "KEY",
                "item_category": "Fabricated",
                "procurement_type": "MAKE",
                "loss_rate": 0.02,
                "unit_price": 680,
                "source_reference": "CAD-SUB-DRV-2100-001",
                "material_name": "铸铝壳体",
                "specification": "AL-356-T6",
                "unit": "PCS",
                "drawing_no": "DWG-CAS-3100",
                "revision": "A",
            },
            {
                "parent_item_code": "SUB-DRV-2100",
                "child_item_code": "SHA-3200",
                "quantity": 1,
                "find_number": "102",
                "component_type": "KEY",
                "item_category": "Fabricated",
                "procurement_type": "MAKE",
                "loss_rate": 0.02,
                "unit_price": 460,
                "source_reference": "CAD-SUB-DRV-2100-002",
                "material_name": "主轴",
                "specification": "40Cr φ28x286",
                "unit": "PCS",
                "drawing_no": "DWG-SHA-3200",
                "revision": "B",
            },
            {
                "parent_item_code": "SUB-DRV-2100",
                "child_item_code": "BRG-6205",
                "quantity": 2,
                "find_number": "103",
                "component_type": "KEY",
                "item_category": "Standard",
                "procurement_type": "BUY",
                "unit_price": 38,
                "source_reference": "CAD-SUB-DRV-2100-003",
                "material_name": "深沟球轴承 6205",
                "specification": "6205-2RS",
                "unit": "PCS",
                "drawing_no": "STD-BRG-6205",
                "revision": "A",
            },
            {
                "parent_item_code": "SUB-DRV-2100",
                "child_item_code": "CPL-3300",
                "quantity": 1,
                "find_number": "104",
                "component_type": "NORMAL",
                "item_category": "Standard",
                "procurement_type": "BUY",
                "unit_price": 96,
                "source_reference": "CAD-SUB-DRV-2100-004",
                "material_name": "弹性联轴器",
                "specification": "D28-L35",
                "unit": "PCS",
                "drawing_no": "STD-CPL-3300",
                "revision": "A",
            },
            {
                "parent_item_code": "SUB-DRV-2100",
                "child_item_code": "FLT-3400",
                "quantity": 1,
                "find_number": "105",
                "component_type": "NORMAL",
                "item_category": "Fabricated",
                "procurement_type": "MAKE",
                "loss_rate": 0.02,
                "unit_price": 135,
                "source_reference": "CAD-SUB-DRV-2100-005",
                "material_name": "安装法兰",
                "specification": "Q235B t12",
                "unit": "PCS",
                "drawing_no": "DWG-FLT-3400",
                "revision": "A",
            },
        ],
    },
    {
        "header": {
            "product_code": "ASM-SRV-1001",
            "product_name": "伺服传动总成",
            "version": "v1.1",
            "bom_type": "EBOM",
            "status": "RELEASED",
            "description": "优化版工程 BOM，增加密封挡圈并更新紧固件需求。",
            "is_active": True,
            "product_family": "包装机模组",
            "business_unit": "智能装备事业部",
            "project_code": "PRJ-2026-001",
            "plant_code": "M01",
            "discipline": "机械装配",
            "source_system": "SOLIDWORKS",
            "source_file": "SolidWorks/ASM-SRV-1001_v1.1.SLDASM",
            "sync_status": "SYNCED",
            "cad_document_no": "DWG-ASM-SRV-1001",
            "released_by": "PLM自动同步",
            "last_synced_at": datetime(2026, 4, 23, 10, 30, 0),
        },
        "items": [
            {
                "parent_item_code": "ASM-SRV-1001",
                "child_item_code": "SUB-DRV-2100",
                "quantity": 1,
                "find_number": "001",
                "component_type": "KEY",
                "item_category": "Assembly",
                "procurement_type": "MAKE",
                "unit_price": 1910,
                "source_reference": "CAD-ASM-SRV-1001-001",
                "material_name": "传动子装配",
                "specification": "SUB-DRV-2100",
                "unit": "SET",
                "drawing_no": "DWG-SUB-DRV-2100",
                "revision": "B",
            },
            {
                "parent_item_code": "ASM-SRV-1001",
                "child_item_code": "MTR-4000",
                "quantity": 1,
                "find_number": "002",
                "component_type": "KEY",
                "item_category": "Purchased",
                "procurement_type": "BUY",
                "loss_rate": 0.01,
                "unit_price": 1280,
                "source_reference": "CAD-ASM-SRV-1001-002",
                "material_name": "750W 伺服电机",
                "specification": "AC750W-220V",
                "unit": "PCS",
                "drawing_no": "PUR-MTR-4000",
                "revision": "A",
            },
            {
                "parent_item_code": "ASM-SRV-1001",
                "child_item_code": "ENC-4100",
                "quantity": 1,
                "find_number": "003",
                "component_type": "NORMAL",
                "item_category": "Purchased",
                "procurement_type": "BUY",
                "unit_price": 420,
                "source_reference": "CAD-ASM-SRV-1001-003",
                "material_name": "编码器组件",
                "specification": "17bit ABS",
                "unit": "PCS",
                "drawing_no": "PUR-ENC-4100",
                "revision": "A",
            },
            {
                "parent_item_code": "ASM-SRV-1001",
                "child_item_code": "BLT-M8X25",
                "quantity": 10,
                "find_number": "004",
                "component_type": "NORMAL",
                "item_category": "Standard",
                "procurement_type": "BUY",
                "loss_rate": 0.03,
                "unit_price": 1.6,
                "source_reference": "CAD-ASM-SRV-1001-004",
                "material_name": "内六角螺栓 M8x25",
                "specification": "12.9级",
                "unit": "PCS",
                "drawing_no": "STD-BLT-M8X25",
                "revision": "A",
            },
            {
                "parent_item_code": "ASM-SRV-1001",
                "child_item_code": "WSH-M8",
                "quantity": 10,
                "find_number": "005",
                "component_type": "NORMAL",
                "item_category": "Standard",
                "procurement_type": "BUY",
                "loss_rate": 0.03,
                "unit_price": 0.35,
                "source_reference": "CAD-ASM-SRV-1001-005",
                "material_name": "平垫圈 M8",
                "specification": "304",
                "unit": "PCS",
                "drawing_no": "STD-WSH-M8",
                "revision": "A",
            },
            {
                "parent_item_code": "SUB-DRV-2100",
                "child_item_code": "CAS-3100",
                "quantity": 1,
                "find_number": "101",
                "component_type": "KEY",
                "item_category": "Fabricated",
                "procurement_type": "MAKE",
                "loss_rate": 0.02,
                "unit_price": 680,
                "source_reference": "CAD-SUB-DRV-2100-001",
                "material_name": "铸铝壳体",
                "specification": "AL-356-T6",
                "unit": "PCS",
                "drawing_no": "DWG-CAS-3100",
                "revision": "A",
            },
            {
                "parent_item_code": "SUB-DRV-2100",
                "child_item_code": "SHA-3200",
                "quantity": 1,
                "find_number": "102",
                "component_type": "KEY",
                "item_category": "Fabricated",
                "procurement_type": "MAKE",
                "loss_rate": 0.02,
                "unit_price": 460,
                "source_reference": "CAD-SUB-DRV-2100-002",
                "material_name": "主轴",
                "specification": "40Cr φ28x286",
                "unit": "PCS",
                "drawing_no": "DWG-SHA-3200",
                "revision": "B",
            },
            {
                "parent_item_code": "SUB-DRV-2100",
                "child_item_code": "BRG-6205",
                "quantity": 2,
                "find_number": "103",
                "component_type": "KEY",
                "item_category": "Standard",
                "procurement_type": "BUY",
                "unit_price": 38,
                "source_reference": "CAD-SUB-DRV-2100-003",
                "material_name": "深沟球轴承 6205",
                "specification": "6205-2RS",
                "unit": "PCS",
                "drawing_no": "STD-BRG-6205",
                "revision": "A",
            },
            {
                "parent_item_code": "SUB-DRV-2100",
                "child_item_code": "CPL-3300",
                "quantity": 1,
                "find_number": "104",
                "component_type": "NORMAL",
                "item_category": "Standard",
                "procurement_type": "BUY",
                "unit_price": 96,
                "source_reference": "CAD-SUB-DRV-2100-004",
                "material_name": "弹性联轴器",
                "specification": "D28-L35",
                "unit": "PCS",
                "drawing_no": "STD-CPL-3300",
                "revision": "A",
            },
            {
                "parent_item_code": "SUB-DRV-2100",
                "child_item_code": "FLT-3400",
                "quantity": 1,
                "find_number": "105",
                "component_type": "NORMAL",
                "item_category": "Fabricated",
                "procurement_type": "MAKE",
                "loss_rate": 0.02,
                "unit_price": 135,
                "source_reference": "CAD-SUB-DRV-2100-005",
                "material_name": "安装法兰",
                "specification": "Q235B t12",
                "unit": "PCS",
                "drawing_no": "DWG-FLT-3400",
                "revision": "A",
            },
            {
                "parent_item_code": "SUB-DRV-2100",
                "child_item_code": "RNG-3500",
                "quantity": 1,
                "find_number": "106",
                "component_type": "NORMAL",
                "item_category": "Standard",
                "procurement_type": "BUY",
                "unit_price": 12,
                "source_reference": "CAD-SUB-DRV-2100-006",
                "material_name": "密封挡圈",
                "specification": "NBR-35",
                "unit": "PCS",
                "drawing_no": "STD-RNG-3500",
                "revision": "A",
            },
        ],
    },
    {
        "header": {
            "product_code": "ASM-SRV-1001",
            "product_name": "伺服传动总成",
            "version": "v1.1",
            "bom_type": "PBOM",
            "status": "RELEASED",
            "description": "工艺版 BOM，面向领料、装配与工位报工。",
            "is_active": True,
            "product_family": "包装机模组",
            "business_unit": "智能装备事业部",
            "project_code": "PRJ-2026-001",
            "plant_code": "M01",
            "discipline": "装配工艺",
            "source_system": "MANUAL",
            "source_file": "Process/ASM-SRV-1001_v1.1.xlsx",
            "sync_status": "SYNCED",
            "cad_document_no": "DWG-ASM-SRV-1001",
            "released_by": "工艺工程师",
            "last_synced_at": datetime(2026, 4, 23, 11, 0, 0),
        },
        "items": [
            {
                "parent_item_code": "ASM-SRV-1001",
                "child_item_code": "CAS-3100",
                "quantity": 1,
                "find_number": "010",
                "component_type": "KEY",
                "routing_link": "OP10-壳体加工",
                "item_category": "Fabricated",
                "procurement_type": "MAKE",
                "loss_rate": 0.02,
                "unit_price": 680,
                "source_reference": "PBOM-OP10",
                "material_name": "铸铝壳体",
                "specification": "AL-356-T6",
                "unit": "PCS",
                "drawing_no": "DWG-CAS-3100",
                "revision": "A",
            },
            {
                "parent_item_code": "ASM-SRV-1001",
                "child_item_code": "SHA-3200",
                "quantity": 1,
                "find_number": "020",
                "component_type": "KEY",
                "routing_link": "OP20-主轴精加工",
                "item_category": "Fabricated",
                "procurement_type": "MAKE",
                "loss_rate": 0.02,
                "unit_price": 460,
                "source_reference": "PBOM-OP20",
                "material_name": "主轴",
                "specification": "40Cr φ28x286",
                "unit": "PCS",
                "drawing_no": "DWG-SHA-3200",
                "revision": "B",
            },
            {
                "parent_item_code": "ASM-SRV-1001",
                "child_item_code": "BRG-6205",
                "quantity": 2,
                "find_number": "030",
                "component_type": "KEY",
                "routing_link": "OP30-轴承装配",
                "item_category": "Standard",
                "procurement_type": "BUY",
                "unit_price": 38,
                "source_reference": "PBOM-OP30",
                "material_name": "深沟球轴承 6205",
                "specification": "6205-2RS",
                "unit": "PCS",
                "drawing_no": "STD-BRG-6205",
                "revision": "A",
            },
            {
                "parent_item_code": "ASM-SRV-1001",
                "child_item_code": "RNG-3500",
                "quantity": 1,
                "find_number": "031",
                "component_type": "NORMAL",
                "routing_link": "OP30-轴承装配",
                "item_category": "Standard",
                "procurement_type": "BUY",
                "unit_price": 12,
                "source_reference": "PBOM-OP30",
                "material_name": "密封挡圈",
                "specification": "NBR-35",
                "unit": "PCS",
                "drawing_no": "STD-RNG-3500",
                "revision": "A",
            },
            {
                "parent_item_code": "ASM-SRV-1001",
                "child_item_code": "CPL-3300",
                "quantity": 1,
                "find_number": "040",
                "component_type": "NORMAL",
                "routing_link": "OP40-联轴器安装",
                "item_category": "Standard",
                "procurement_type": "BUY",
                "unit_price": 96,
                "source_reference": "PBOM-OP40",
                "material_name": "弹性联轴器",
                "specification": "D28-L35",
                "unit": "PCS",
                "drawing_no": "STD-CPL-3300",
                "revision": "A",
            },
            {
                "parent_item_code": "ASM-SRV-1001",
                "child_item_code": "FLT-3400",
                "quantity": 1,
                "find_number": "050",
                "component_type": "NORMAL",
                "routing_link": "OP10-壳体加工",
                "item_category": "Fabricated",
                "procurement_type": "MAKE",
                "loss_rate": 0.02,
                "unit_price": 135,
                "source_reference": "PBOM-OP10",
                "material_name": "安装法兰",
                "specification": "Q235B t12",
                "unit": "PCS",
                "drawing_no": "DWG-FLT-3400",
                "revision": "A",
            },
            {
                "parent_item_code": "ASM-SRV-1001",
                "child_item_code": "MTR-4000",
                "quantity": 1,
                "find_number": "060",
                "component_type": "KEY",
                "routing_link": "OP50-电机安装",
                "item_category": "Purchased",
                "procurement_type": "BUY",
                "loss_rate": 0.01,
                "unit_price": 1280,
                "source_reference": "PBOM-OP50",
                "material_name": "750W 伺服电机",
                "specification": "AC750W-220V",
                "unit": "PCS",
                "drawing_no": "PUR-MTR-4000",
                "revision": "A",
            },
            {
                "parent_item_code": "ASM-SRV-1001",
                "child_item_code": "ENC-4100",
                "quantity": 1,
                "find_number": "061",
                "component_type": "NORMAL",
                "routing_link": "OP50-电机安装",
                "item_category": "Purchased",
                "procurement_type": "BUY",
                "unit_price": 420,
                "source_reference": "PBOM-OP50",
                "material_name": "编码器组件",
                "specification": "17bit ABS",
                "unit": "PCS",
                "drawing_no": "PUR-ENC-4100",
                "revision": "A",
            },
            {
                "parent_item_code": "ASM-SRV-1001",
                "child_item_code": "BLT-M8X25",
                "quantity": 10,
                "find_number": "070",
                "component_type": "NORMAL",
                "routing_link": "OP60-总装锁附",
                "item_category": "Standard",
                "procurement_type": "BUY",
                "loss_rate": 0.03,
                "unit_price": 1.6,
                "source_reference": "PBOM-OP60",
                "material_name": "内六角螺栓 M8x25",
                "specification": "12.9级",
                "unit": "PCS",
                "drawing_no": "STD-BLT-M8X25",
                "revision": "A",
            },
            {
                "parent_item_code": "ASM-SRV-1001",
                "child_item_code": "WSH-M8",
                "quantity": 10,
                "find_number": "071",
                "component_type": "NORMAL",
                "routing_link": "OP60-总装锁附",
                "item_category": "Standard",
                "procurement_type": "BUY",
                "loss_rate": 0.03,
                "unit_price": 0.35,
                "source_reference": "PBOM-OP60",
                "material_name": "平垫圈 M8",
                "specification": "304",
                "unit": "PCS",
                "drawing_no": "STD-WSH-M8",
                "revision": "A",
            },
        ],
    },
    {
        "header": {
            "product_code": "JIG-CLP-2001",
            "product_name": "夹紧治具总成",
            "version": "v1.0",
            "bom_type": "EBOM",
            "status": "RELEASED",
            "description": "治具工程 BOM，用于展示多产品参考版本。",
            "is_active": True,
            "product_family": "工装夹具",
            "business_unit": "自动化产线事业部",
            "project_code": "PRJ-2026-015",
            "plant_code": "M02",
            "discipline": "工装设计",
            "source_system": "EXCEL",
            "source_file": "Import/JIG-CLP-2001_v1.0.xlsx",
            "sync_status": "SYNCED",
            "cad_document_no": "DWG-JIG-CLP-2001",
            "released_by": "工装工程师",
            "last_synced_at": datetime(2026, 4, 23, 11, 15, 0),
        },
        "items": [
            {
                "parent_item_code": "JIG-CLP-2001",
                "child_item_code": "JAW-3600",
                "quantity": 1,
                "find_number": "001",
                "component_type": "KEY",
                "item_category": "Fabricated",
                "procurement_type": "MAKE",
                "loss_rate": 0.02,
                "unit_price": 320,
                "source_reference": "JIG-EBOM-001",
                "material_name": "夹爪底座",
                "specification": "45# φ110",
                "unit": "PCS",
                "drawing_no": "DWG-JAW-3600",
                "revision": "A",
            },
            {
                "parent_item_code": "JIG-CLP-2001",
                "child_item_code": "CYL-5200",
                "quantity": 1,
                "find_number": "002",
                "component_type": "KEY",
                "item_category": "Purchased",
                "procurement_type": "BUY",
                "unit_price": 260,
                "source_reference": "JIG-EBOM-002",
                "material_name": "气缸组件",
                "specification": "SC50x100",
                "unit": "PCS",
                "drawing_no": "PUR-CYL-5200",
                "revision": "A",
            },
            {
                "parent_item_code": "JIG-CLP-2001",
                "child_item_code": "SNS-5300",
                "quantity": 2,
                "find_number": "003",
                "component_type": "NORMAL",
                "item_category": "Purchased",
                "procurement_type": "BUY",
                "unit_price": 78,
                "source_reference": "JIG-EBOM-003",
                "material_name": "行程传感器",
                "specification": "PNP M12",
                "unit": "PCS",
                "drawing_no": "PUR-SNS-5300",
                "revision": "A",
            },
            {
                "parent_item_code": "JIG-CLP-2001",
                "child_item_code": "BLT-M8X25",
                "quantity": 6,
                "find_number": "004",
                "component_type": "NORMAL",
                "item_category": "Standard",
                "procurement_type": "BUY",
                "loss_rate": 0.03,
                "unit_price": 1.6,
                "source_reference": "JIG-EBOM-004",
                "material_name": "内六角螺栓 M8x25",
                "specification": "12.9级",
                "unit": "PCS",
                "drawing_no": "STD-BLT-M8X25",
                "revision": "A",
            },
            {
                "parent_item_code": "JIG-CLP-2001",
                "child_item_code": "WSH-M8",
                "quantity": 6,
                "find_number": "005",
                "component_type": "NORMAL",
                "item_category": "Standard",
                "procurement_type": "BUY",
                "loss_rate": 0.03,
                "unit_price": 0.35,
                "source_reference": "JIG-EBOM-005",
                "material_name": "平垫圈 M8",
                "specification": "304",
                "unit": "PCS",
                "drawing_no": "STD-WSH-M8",
                "revision": "A",
            },
        ],
    },
    {
        "header": {
            "product_code": "JIG-CLP-2001",
            "product_name": "夹紧治具总成",
            "version": "v1.0",
            "bom_type": "MBOM",
            "status": "RELEASED",
            "description": "制造发料 BOM，用于 WIP 配套与仓储发料。",
            "is_active": True,
            "product_family": "工装夹具",
            "business_unit": "自动化产线事业部",
            "project_code": "PRJ-2026-015",
            "plant_code": "M02",
            "discipline": "车间执行",
            "source_system": "MANUAL",
            "source_file": "WMS/JIG-CLP-2001_kit.xlsx",
            "sync_status": "SYNCED",
            "cad_document_no": "DWG-JIG-CLP-2001",
            "released_by": "制造工程师",
            "last_synced_at": datetime(2026, 4, 23, 11, 40, 0),
        },
        "items": [
            {
                "parent_item_code": "JIG-CLP-2001",
                "child_item_code": "JAW-3600",
                "quantity": 1,
                "find_number": "K01",
                "component_type": "KEY",
                "routing_link": "KIT-A",
                "item_category": "Fabricated",
                "procurement_type": "MAKE",
                "loss_rate": 0.02,
                "unit_price": 320,
                "source_reference": "MBOM-KIT-A",
                "material_name": "夹爪底座",
                "specification": "45# φ110",
                "unit": "PCS",
                "drawing_no": "DWG-JAW-3600",
                "revision": "A",
            },
            {
                "parent_item_code": "JIG-CLP-2001",
                "child_item_code": "CYL-5200",
                "quantity": 1,
                "find_number": "K02",
                "component_type": "KEY",
                "routing_link": "KIT-B",
                "item_category": "Purchased",
                "procurement_type": "BUY",
                "unit_price": 260,
                "source_reference": "MBOM-KIT-B",
                "material_name": "气缸组件",
                "specification": "SC50x100",
                "unit": "PCS",
                "drawing_no": "PUR-CYL-5200",
                "revision": "A",
            },
            {
                "parent_item_code": "JIG-CLP-2001",
                "child_item_code": "SNS-5300",
                "quantity": 2,
                "find_number": "K03",
                "component_type": "NORMAL",
                "routing_link": "KIT-B",
                "item_category": "Purchased",
                "procurement_type": "BUY",
                "unit_price": 78,
                "source_reference": "MBOM-KIT-B",
                "material_name": "行程传感器",
                "specification": "PNP M12",
                "unit": "PCS",
                "drawing_no": "PUR-SNS-5300",
                "revision": "A",
            },
            {
                "parent_item_code": "JIG-CLP-2001",
                "child_item_code": "BLT-M8X25",
                "quantity": 6,
                "find_number": "K04",
                "component_type": "NORMAL",
                "routing_link": "KIT-C",
                "item_category": "Standard",
                "procurement_type": "BUY",
                "loss_rate": 0.03,
                "unit_price": 1.6,
                "source_reference": "MBOM-KIT-C",
                "material_name": "内六角螺栓 M8x25",
                "specification": "12.9级",
                "unit": "PCS",
                "drawing_no": "STD-BLT-M8X25",
                "revision": "A",
            },
            {
                "parent_item_code": "JIG-CLP-2001",
                "child_item_code": "WSH-M8",
                "quantity": 6,
                "find_number": "K05",
                "component_type": "NORMAL",
                "routing_link": "KIT-C",
                "item_category": "Standard",
                "procurement_type": "BUY",
                "loss_rate": 0.03,
                "unit_price": 0.35,
                "source_reference": "MBOM-KIT-C",
                "material_name": "平垫圈 M8",
                "specification": "304",
                "unit": "PCS",
                "drawing_no": "STD-WSH-M8",
                "revision": "A",
            },
        ],
    },
]


def ensure_tables() -> None:
    engine = get_default_engine()
    Base.metadata.create_all(
        bind=engine,
        tables=[Material.__table__, BOMHeader.__table__, BOMItem.__table__],
    )
    ensure_schema_compatibility(engine)


def upsert_material(db, payload: Dict[str, Any]) -> Material:
    material = db.query(Material).filter(Material.code == payload["code"]).first()
    if material is None:
        material = Material(code=payload["code"], name=payload["name"])
        db.add(material)

    for field, value in payload.items():
        setattr(material, field, value)

    db.flush()
    return material


def upsert_bom_header(db, payload: Dict[str, Any]) -> BOMHeader:
    header = (
        db.query(BOMHeader)
        .filter(
            BOMHeader.product_code == payload["product_code"],
            BOMHeader.version == payload["version"],
            BOMHeader.bom_type == payload["bom_type"],
        )
        .first()
    )

    if header is None:
        header = BOMHeader()
        db.add(header)

    for field in [
        "product_code",
        "version",
        "bom_type",
        "status",
        "description",
        "is_active",
        "effective_date",
        "expiry_date",
        "product_family",
        "business_unit",
        "project_code",
        "plant_code",
        "discipline",
        "source_system",
        "source_file",
        "sync_status",
        "cad_document_no",
        "released_by",
        "last_synced_at",
    ]:
        if field in payload:
            setattr(header, field, payload[field])

    if not header.effective_date:
        header.effective_date = datetime.utcnow()
    if not header.version:
        header.version = "v1.0"
    if not header.bom_type:
        header.bom_type = "EBOM"
    if not header.status:
        header.status = "DRAFT"
    if header.is_active is None:
        header.is_active = True

    db.flush()

    if header.is_active:
        (
            db.query(BOMHeader)
            .filter(
                BOMHeader.product_code == header.product_code,
                BOMHeader.bom_type == header.bom_type,
                BOMHeader.id != header.id,
            )
            .update({"is_active": False}, synchronize_session=False)
        )

    return header


def seed_sample_bom_data() -> None:
    ensure_tables()
    db = SessionLocal()

    try:
        for payload in MATERIALS:
            upsert_material(db, payload)

        for definition in BOM_DEFINITIONS:
            header_payload = dict(definition["header"])
            header = upsert_bom_header(db, header_payload)

            PLMService.upsert_material_by_code(
                db,
                code=header.product_code,
                payload={
                    "name": header_payload.get("product_name") or header.product_code,
                    "category": header.product_family,
                    "unit": "SET",
                    "material_type": "FINISHED",
                    "drawing_no": header.cad_document_no,
                    "revision": "A",
                },
            )

            normalized_items = PLMService._normalize_bom_items(header.product_code, definition["items"])
            PLMService.replace_bom_items(db, header.id, normalized_items)

        db.commit()
        print(f"Seeded {len(MATERIALS)} materials and {len(BOM_DEFINITIONS)} BOM headers.")
    except Exception:
        db.rollback()
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed_sample_bom_data()
